from . import test_reglas
from . import test_libro
from . import test_compras
from . import test_canjes
from . import test_app
from . import test_seguridad_rpc
from . import test_roles
from . import test_socios_web
from . import test_factura_impresa
from . import test_premio_ejemplo
