from . import formato
from . import lineas
from . import account_move
from . import account_move_line
from . import ir_actions_report
from . import ir_qweb_fields
from . import res_company
from . import res_partner
from . import sale_order
