from . import test_registro
from . import test_nucleo
from . import test_interfaz_brian
from . import test_mcp
from . import test_telegram
from . import test_herramientas
from . import test_seguridad_rpc
from . import test_historial
from . import test_adjuntos
from . import test_importacion
from . import test_herramientas_contabilidad
from . import test_ronda6
