from . import test_website_dcasa
from . import test_tienda
from . import test_seo_y_promesas
from . import test_roles
from . import test_itbms
from . import test_legal
from . import test_imagen
from . import test_black_weekend
from . import test_diseno
